### ISSUE TITLE
Is there a way to test this code on Mac OS X?

### ISSUE THREAD

**Issue by alcarvalho** [ppissanetzky/AndThen#1]
I'm trying to write some tests for the library with busted, but I can't find a way to implement the 'dolater' function on Mac OS X.

I have tried several thread libraries but none seem to fit.

**Comment by ppissanetzky** [comment]
Maybe you can try https://github.com/Tieske/CopasTimer?

**Comment by alcarvalho** [comment]
Thank you very much! This did the trick. As soon as I finish this project I'm currently working I'll write tests for this library and create PR. It's working greatly btw. Thanks for publishing it.
